/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessesRouteImport } from './routes/successes'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RecurrentImplantationRouteImport } from './routes/recurrent-implantation'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as PgtRouteImport } from './routes/pgt'
import { Route as OncofertilityRouteImport } from './routes/oncofertility'
import { Route as NiptRouteImport } from './routes/nipt'
import { Route as IvfRouteImport } from './routes/ivf'
import { Route as IcsiRouteImport } from './routes/icsi'
import { Route as GeneticTestingRouteImport } from './routes/genetic-testing'
import { Route as FrozenEmbryoTransferRouteImport } from './routes/frozen-embryo-transfer'
import { Route as EmbryoscopeRouteImport } from './routes/embryoscope'
import { Route as EggFreezingRouteImport } from './routes/egg-freezing'
import { Route as DonorRouteImport } from './routes/donor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlastocystGradingRouteImport } from './routes/blastocyst-grading'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const SuccessesRoute = SuccessesRouteImport.update({
  id: '/successes',
  path: '/successes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrentImplantationRoute = RecurrentImplantationRouteImport.update({
  id: '/recurrent-implantation',
  path: '/recurrent-implantation',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PgtRoute = PgtRouteImport.update({
  id: '/pgt',
  path: '/pgt',
  getParentRoute: () => rootRouteImport,
} as any)
const OncofertilityRoute = OncofertilityRouteImport.update({
  id: '/oncofertility',
  path: '/oncofertility',
  getParentRoute: () => rootRouteImport,
} as any)
const NiptRoute = NiptRouteImport.update({
  id: '/nipt',
  path: '/nipt',
  getParentRoute: () => rootRouteImport,
} as any)
const IvfRoute = IvfRouteImport.update({
  id: '/ivf',
  path: '/ivf',
  getParentRoute: () => rootRouteImport,
} as any)
const IcsiRoute = IcsiRouteImport.update({
  id: '/icsi',
  path: '/icsi',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneticTestingRoute = GeneticTestingRouteImport.update({
  id: '/genetic-testing',
  path: '/genetic-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const FrozenEmbryoTransferRoute = FrozenEmbryoTransferRouteImport.update({
  id: '/frozen-embryo-transfer',
  path: '/frozen-embryo-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbryoscopeRoute = EmbryoscopeRouteImport.update({
  id: '/embryoscope',
  path: '/embryoscope',
  getParentRoute: () => rootRouteImport,
} as any)
const EggFreezingRoute = EggFreezingRouteImport.update({
  id: '/egg-freezing',
  path: '/egg-freezing',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorRoute = DonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastocystGradingRoute = BlastocystGradingRouteImport.update({
  id: '/blastocyst-grading',
  path: '/blastocyst-grading',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blastocyst-grading': typeof BlastocystGradingRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/donor': typeof DonorRoute
  '/egg-freezing': typeof EggFreezingRoute
  '/embryoscope': typeof EmbryoscopeRoute
  '/frozen-embryo-transfer': typeof FrozenEmbryoTransferRoute
  '/genetic-testing': typeof GeneticTestingRoute
  '/icsi': typeof IcsiRoute
  '/ivf': typeof IvfRoute
  '/nipt': typeof NiptRoute
  '/oncofertility': typeof OncofertilityRoute
  '/pgt': typeof PgtRoute
  '/prices': typeof PricesRoute
  '/recurrent-implantation': typeof RecurrentImplantationRoute
  '/services': typeof ServicesRoute
  '/successes': typeof SuccessesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blastocyst-grading': typeof BlastocystGradingRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/donor': typeof DonorRoute
  '/egg-freezing': typeof EggFreezingRoute
  '/embryoscope': typeof EmbryoscopeRoute
  '/frozen-embryo-transfer': typeof FrozenEmbryoTransferRoute
  '/genetic-testing': typeof GeneticTestingRoute
  '/icsi': typeof IcsiRoute
  '/ivf': typeof IvfRoute
  '/nipt': typeof NiptRoute
  '/oncofertility': typeof OncofertilityRoute
  '/pgt': typeof PgtRoute
  '/prices': typeof PricesRoute
  '/recurrent-implantation': typeof RecurrentImplantationRoute
  '/services': typeof ServicesRoute
  '/successes': typeof SuccessesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blastocyst-grading': typeof BlastocystGradingRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/donor': typeof DonorRoute
  '/egg-freezing': typeof EggFreezingRoute
  '/embryoscope': typeof EmbryoscopeRoute
  '/frozen-embryo-transfer': typeof FrozenEmbryoTransferRoute
  '/genetic-testing': typeof GeneticTestingRoute
  '/icsi': typeof IcsiRoute
  '/ivf': typeof IvfRoute
  '/nipt': typeof NiptRoute
  '/oncofertility': typeof OncofertilityRoute
  '/pgt': typeof PgtRoute
  '/prices': typeof PricesRoute
  '/recurrent-implantation': typeof RecurrentImplantationRoute
  '/services': typeof ServicesRoute
  '/successes': typeof SuccessesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blastocyst-grading'
    | '/booking'
    | '/contact'
    | '/donor'
    | '/egg-freezing'
    | '/embryoscope'
    | '/frozen-embryo-transfer'
    | '/genetic-testing'
    | '/icsi'
    | '/ivf'
    | '/nipt'
    | '/oncofertility'
    | '/pgt'
    | '/prices'
    | '/recurrent-implantation'
    | '/services'
    | '/successes'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/blog/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blastocyst-grading'
    | '/booking'
    | '/contact'
    | '/donor'
    | '/egg-freezing'
    | '/embryoscope'
    | '/frozen-embryo-transfer'
    | '/genetic-testing'
    | '/icsi'
    | '/ivf'
    | '/nipt'
    | '/oncofertility'
    | '/pgt'
    | '/prices'
    | '/recurrent-implantation'
    | '/services'
    | '/successes'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/blog'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blastocyst-grading'
    | '/booking'
    | '/contact'
    | '/donor'
    | '/egg-freezing'
    | '/embryoscope'
    | '/frozen-embryo-transfer'
    | '/genetic-testing'
    | '/icsi'
    | '/ivf'
    | '/nipt'
    | '/oncofertility'
    | '/pgt'
    | '/prices'
    | '/recurrent-implantation'
    | '/services'
    | '/successes'
    | '/blog/$slug'
    | '/guides/$slug'
    | '/blog/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlastocystGradingRoute: typeof BlastocystGradingRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  DonorRoute: typeof DonorRoute
  EggFreezingRoute: typeof EggFreezingRoute
  EmbryoscopeRoute: typeof EmbryoscopeRoute
  FrozenEmbryoTransferRoute: typeof FrozenEmbryoTransferRoute
  GeneticTestingRoute: typeof GeneticTestingRoute
  IcsiRoute: typeof IcsiRoute
  IvfRoute: typeof IvfRoute
  NiptRoute: typeof NiptRoute
  OncofertilityRoute: typeof OncofertilityRoute
  PgtRoute: typeof PgtRoute
  PricesRoute: typeof PricesRoute
  RecurrentImplantationRoute: typeof RecurrentImplantationRoute
  ServicesRoute: typeof ServicesRoute
  SuccessesRoute: typeof SuccessesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/successes': {
      id: '/successes'
      path: '/successes'
      fullPath: '/successes'
      preLoaderRoute: typeof SuccessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrent-implantation': {
      id: '/recurrent-implantation'
      path: '/recurrent-implantation'
      fullPath: '/recurrent-implantation'
      preLoaderRoute: typeof RecurrentImplantationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pgt': {
      id: '/pgt'
      path: '/pgt'
      fullPath: '/pgt'
      preLoaderRoute: typeof PgtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oncofertility': {
      id: '/oncofertility'
      path: '/oncofertility'
      fullPath: '/oncofertility'
      preLoaderRoute: typeof OncofertilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nipt': {
      id: '/nipt'
      path: '/nipt'
      fullPath: '/nipt'
      preLoaderRoute: typeof NiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ivf': {
      id: '/ivf'
      path: '/ivf'
      fullPath: '/ivf'
      preLoaderRoute: typeof IvfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icsi': {
      id: '/icsi'
      path: '/icsi'
      fullPath: '/icsi'
      preLoaderRoute: typeof IcsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genetic-testing': {
      id: '/genetic-testing'
      path: '/genetic-testing'
      fullPath: '/genetic-testing'
      preLoaderRoute: typeof GeneticTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frozen-embryo-transfer': {
      id: '/frozen-embryo-transfer'
      path: '/frozen-embryo-transfer'
      fullPath: '/frozen-embryo-transfer'
      preLoaderRoute: typeof FrozenEmbryoTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embryoscope': {
      id: '/embryoscope'
      path: '/embryoscope'
      fullPath: '/embryoscope'
      preLoaderRoute: typeof EmbryoscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egg-freezing': {
      id: '/egg-freezing'
      path: '/egg-freezing'
      fullPath: '/egg-freezing'
      preLoaderRoute: typeof EggFreezingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor': {
      id: '/donor'
      path: '/donor'
      fullPath: '/donor'
      preLoaderRoute: typeof DonorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blastocyst-grading': {
      id: '/blastocyst-grading'
      path: '/blastocyst-grading'
      fullPath: '/blastocyst-grading'
      preLoaderRoute: typeof BlastocystGradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlastocystGradingRoute: BlastocystGradingRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  DonorRoute: DonorRoute,
  EggFreezingRoute: EggFreezingRoute,
  EmbryoscopeRoute: EmbryoscopeRoute,
  FrozenEmbryoTransferRoute: FrozenEmbryoTransferRoute,
  GeneticTestingRoute: GeneticTestingRoute,
  IcsiRoute: IcsiRoute,
  IvfRoute: IvfRoute,
  NiptRoute: NiptRoute,
  OncofertilityRoute: OncofertilityRoute,
  PgtRoute: PgtRoute,
  PricesRoute: PricesRoute,
  RecurrentImplantationRoute: RecurrentImplantationRoute,
  ServicesRoute: ServicesRoute,
  SuccessesRoute: SuccessesRoute,
  BlogSlugRoute: BlogSlugRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
